// js/receitas.js (FINAL, COMPLETO E CORRIGIDO)
document.addEventListener('DOMContentLoaded', () => {

    // A lista de receitas completa com todos os dados
    const RECIPES = [
      {id:'panqueca-banana',title:'Panqueca Integral de Banana',desc:'Panquecas fáceis e econômicas com banana madura e aveia—sem açúcar refinado.',image:'img/panqueca-banana.png',type:'cafe',tags:['vegetariana'],time:20,difficulty:'fácil',yield:'6 unidades',ingredients:['2 bananas maduras','1 xícara de aveia em flocos','1 ovo','1/2 xícara de leite (ou vegetal)','1 colher de chá de fermento em pó','pitada de sal'],steps:['Amasse as bananas até formar um purê.','Misture a aveia, ovo e leite até obter massa homogênea.','Aqueça frigideira antiaderente e faça porções.','Cozinhe 2-3 min cada lado até dourar.'],tips:['Use casca de banana ralada em receitas doces (se bem lavada).','Congelar bananas maduras para futuras panquecas.'],impact:{wasteAvoided_g:120}},
      {id:'overnight-oats-maca',title:'Overnight Oats com Maçã e Canela',desc:'Aveia preparada de véspera com maçã ralada e canela — prático e nutritivo.',image:'img/overnight-oats.png',type:'cafe',tags:['vegetariana','sem_gluten'],time:10,difficulty:'fácil',yield:'2 porções',ingredients:['1 xícara de aveia sem glúten','1 xícara de leite vegetal','1 maçã ralada (com casca)','1 colher de sopa de mel ou xarope de agave','1 colher de chá de canela','1 colher de sopa de chia (opcional)'],steps:['Misture todos os ingredientes em um pote com tampa.','Tampe e leve à geladeira por pelo menos 4 horas (ou durante a noite).','Sirva frio, com frutas ou sementes por cima.'],tips:['Use casca de maçã bem lavada para fibra extra.','Aproveite sobras de frutas maduras para adoçar naturalmente.'],impact:{wasteAvoided_g:80}},
      {id:'geleia-maca',title:'Geleia de Casca de Maçã',desc:'Geleia feita com cascas de maçã para reduzir desperdício e sabor intenso.',image:'img/geleia-casca-maca.png',type:'cafe',tags:['vegetariana','vegano'],time:90,difficulty:'fácil',yield:'1 vidro (250 ml)',ingredients:['4 maçãs (cascas e aparas bem lavadas)','1 xícara de açúcar','1/2 xícara de água','Suco de 1/2 limão','1 pau de canela (opcional)'],steps:['Coloque as cascas de maçã, água e canela numa panela.','Cozinhe em fogo baixo até as cascas ficarem macias, cerca de 30 minutos.','Retire a canela e bata a mistura no liquidificador.','Volte para panela, acrescente o açúcar e o suco de limão, cozinhe até engrossar.','Despeje em vidro esterilizado e conserve na geladeira.'],tips:['Lave bem as cascas para evitar resíduos.','A canela pode ser substituída por cravo para variar o sabor.','Ideal para pães, torradas e sobremesas.'],impact:{wasteAvoided_g:120}},
      {id:'bolo-mingau-milho',title:'Bolo de Mingau de Milho',desc:'Bolo cremoso e sem glúten feito com sobras de mingau de milho.',image:'img/bolo-mingau-milho.png',type:'cafe',tags:['vegetariana','sem_gluten'],time:60,difficulty:'fácil',yield:'10 porções',ingredients:['2 xícaras de mingau de milho pronto','3 ovos','1/2 xícara de óleo de coco','1 xícara de açúcar demerara','1 xícara de fubá','1 colher de sopa de fermento em pó'],steps:['No liquidificador, bata o mingau de milho, os ovos, o óleo e o açúcar.','Transfira para uma tigela e incorpore o fubá e o fermento.','Despeje em forma untada e enfarinhada.','Asse em forno preaquecido a 180°C por cerca de 40 minutos.'],tips:['Se o mingau já estiver doce, reduza a quantidade de açúcar.','Pode adicionar coco ralado ou erva-doce à massa.'],impact:{wasteAvoided_g:400}},
      {id:'torrada-abacate',title:'Torrada com Abacate e Sementes',desc:'Uma opção de café da manhã rápido, nutritivo e que aproveita pão amanhecido.',image:'img/torrada-abacate.png',type:'cafe',tags:['vegetariana','vegano'],time:10,difficulty:'fácil',yield:'2 porções',ingredients:['2 fatias de pão amanhecido','1/2 abacate maduro','Suco de limão a gosto','Sal e pimenta do reino','Sementes de abóbora e girassol torradas'],steps:['Torre as fatias de pão na torradeira ou frigideira.','Amasse o abacate com um garfo, tempere com limão, sal e pimenta.','Passe a pasta de abacate sobre as torradas.','Salpique as sementes torradas por cima e sirva.'],tips:['Use o caroço do abacate para cultivar uma nova planta.','Sementes de abóbora podem ser torradas com temperos para um lanche.'],impact:{wasteAvoided_g:100}},
      {id:'vitamina-casca-banana',title:'Vitamina com Casca de Banana',desc:'Vitamina nutritiva que utiliza a casca da banana, rica em fibras e nutrientes.',image:'img/vitamina-casca-banana.png',type:'cafe',tags:['vegetariana'],time:5,difficulty:'fácil',yield:'2 copos',ingredients:['1 banana com casca (bem lavada)','1 xícara de leite (ou vegetal)','1 colher de sopa de aveia','Mel ou adoçante a gosto','Gelo (opcional)'],steps:['Lave bem a casca da banana em água corrente.','Pique a banana com a casca em rodelas.','Bata todos os ingredientes no liquidificador até obter uma mistura homogênea.','Sirva imediatamente.'],tips:['Use bananas orgânicas para evitar agrotóxicos na casca.','A casca adiciona uma cremosidade extra à vitamina.'],impact:{wasteAvoided_g:50}},
      {id:'arroz-cremoso',title:'Arroz Cremoso de Talos',desc:'Arroz cremoso e nutritivo feito com talos de vegetais, evitando o desperdício.',image:'img/arroz-cremoso.png',type:'almoco',tags:['vegetariana'],time:30,difficulty:'fácil',yield:'4 porções',ingredients:['1 xícara de talos picados (brócolis, couve-flor, etc)','2 xícaras de arroz cozido','1 cebola picada','2 dentes de alho picados','1/2 xícara de creme de leite (ou de castanhas)','Queijo parmesão ralado a gosto','Sal e pimenta'],steps:['Refogue a cebola e o alho em azeite.','Adicione os talos picados e cozinhe até ficarem macios.','Acrescente o arroz cozido e misture bem.','Incorpore o creme de leite, o queijo ralado e tempere com sal e pimenta.','Sirva quente.'],tips:['Congele talos e folhas em um saco para usar quando tiver uma boa quantidade.','Pode adicionar sobras de frango desfiado ou legumes.'],impact:{wasteAvoided_g:200}},
      {id:'risoto-talhos',title:'Risoto de Talos',desc:'Risoto cremoso que aproveita talos e folhas de vegetais.',image:'img/risoto-talhos.png',type:'almoco',tags:['vegetariana'],time:40,difficulty:'médio',yield:'4 porções',ingredients:['1 xícara de arroz arbóreo','1/2 xícara de talos picados (aipo, brócolis)','1/2 cebola picada','1 litro de caldo de legumes (feito com cascas)','1/2 xícara de vinho branco seco','Queijo parmesão e manteiga para finalizar'],steps:['Refogue a cebola na manteiga, adicione os talos e depois o arroz.','Acrescente o vinho e deixe evaporar.','Vá adicionando o caldo de legumes aos poucos, mexendo sempre, até o arroz cozinhar.','Finalize com parmesão e manteiga.'],tips:['Use as cascas de cebola, cenoura e talos de salsão para fazer o caldo de legumes caseiro.','O segredo do risoto é mexer sempre para liberar o amido do arroz.'],impact:{wasteAvoided_g:250}},
      {id:'quiche-vegetais',title:'Quiche de Vegetais com Sobras',desc:'Quiche versátil para aproveitar sobras de legumes da geladeira.',image:'img/quiche-vegetais.png',type:'almoco',tags:['vegetariana'],time:50,difficulty:'fácil',yield:'6 porções',ingredients:['1 rolo de massa folhada ou de torta','3 ovos','1 xícara de creme de leite','2 xícaras de legumes cozidos picados (sobras)','1/2 xícara de queijo ralado','Sal, pimenta e noz-moscada'],steps:['Forre uma forma de torta com a massa.','Em uma tigela, bata os ovos com o creme de leite e tempere.','Espalhe os legumes sobre a massa e despeje a mistura de ovos por cima.','Polvilhe com o queijo ralado.','Asse em forno a 180°C por cerca de 30-35 minutos.'],tips:['Funciona com quase qualquer legume: brócolis, cenoura, abobrinha, espinafre.','Pode adicionar sobras de frango ou carne também.'],impact:{wasteAvoided_g:300}},
      {id:'salada-quinoa-legumes',title:'Salada de Quinoa com Legumes Assados',desc:'Salada completa e nutritiva, ótima para marmitas e almoços leves.',image:'img/salada-quinoa-legumes.png',type:'almoco',tags:['vegano','sem_gluten'],time:40,difficulty:'fácil',yield:'4 porções',ingredients:['1 xícara de quinoa cozida','2 xícaras de legumes variados em cubos (abobrinha, cenoura, pimentão)','Azeite, sal e ervas a gosto','Suco de 1 limão','Folhas de hortelã fresca'],steps:['Tempere os legumes com azeite, sal e ervas e asse em forno a 200°C até dourarem.','Em uma tigela grande, misture a quinoa cozida com os legumes assados.','Tempere com o suco de limão e mais um fio de azeite.','Finalize com folhas de hortelã fresca.'],tips:['Aproveite as pontas e cascas dos legumes para fazer um caldo.','A salada pode ser guardada na geladeira por até 3 dias.'],impact:{wasteAvoided_g:150}},
      {id:'panini-vegetal',title:'Panini Vegetal',desc:'Sanduíche quente e crocante com pasta de talos e folhas.',image:'img/panini-vegetal.png',type:'lanche',tags:['vegetariana'],time:15,difficulty:'fácil',yield:'2 porções',ingredients:['4 fatias de pão de forma','1 xícara de pasta de talos (ver receita de pesto)','Queijo muçarela a gosto','Rodelas de tomate','Manteiga ou azeite'],steps:['Passe a pasta de talos em duas fatias de pão.','Adicione o queijo e o tomate.','Feche os sanduíches e passe manteiga ou azeite por fora.','Pressione em uma sanduicheira ou frigideira quente até dourar.'],tips:['A pasta de talos pode ser congelada em porções.','Use pão amanhecido para um resultado mais crocante.'],impact:{wasteAvoided_g:100}},
      {id:'omelete-casca-abobrinha',title:'Omelete com Casca de Abobrinha',desc:'Omelete nutritivo que aproveita a casca da abobrinha, rica em fibras.',image:'img/omelete-casca-abobrinha.png',type:'lanche',tags:['vegetariana'],time:15,difficulty:'fácil',yield:'1 porção',ingredients:['2 ovos','Casca de 1 abobrinha ralada','2 colheres de sopa de queijo ralado','Sal e pimenta a gosto','Cebolinha picada'],steps:['Bata os ovos com um garfo e tempere com sal e pimenta.','Incorpore a casca de abobrinha ralada, o queijo e a cebolinha.','Despeje em uma frigideira antiaderente quente com um fio de azeite.','Cozinhe em fogo baixo até firmar, depois dobre ao meio.'],tips:['Lave bem a abobrinha antes de usar a casca.','Pode adicionar outros temperos como orégano ou cúrcuma.'],impact:{wasteAvoided_g:80}},
      {id:'lanche-hummus',title:'Lanche com Hummus de Feijão Branco',desc:'Uma alternativa ao hummus tradicional, feita com feijão branco cozido.',image:'img/lanche-hummus.png',type:'lanche',tags:['vegano','sem_gluten'],time:10,difficulty:'fácil',yield:'4 porções',ingredients:['2 xícaras de feijão branco cozido (sobras)','2 colheres de sopa de azeite','Suco de 1 limão','1 dente de alho','Sal e cominho a gosto'],steps:['Bata todos os ingredientes em um processador ou liquidificador até formar uma pasta cremosa.','Se necessário, adicione um pouco da água do cozimento do feijão para diluir.','Sirva com palitos de cenoura, pepino ou torradas.'],tips:['A água do cozimento do feijão (sem sal) pode ser usada para regar plantas.','O hummus dura até 5 dias na geladeira.'],impact:{wasteAvoided_g:250}},
      {id:'tapioca-queijo',title:'Tapioca com Queijo e Tomate',desc:'Lanche rápido e versátil, sem glúten.',image:'img/tapioca-queijo.png',type:'lanche',tags:['vegetariana','sem_gluten'],time:10,difficulty:'fácil',yield:'1 porção',ingredients:['3 colheres de sopa de goma de tapioca','2 fatias de queijo muçarela','Rodelas de tomate a gosto','Orégano e sal'],steps:['Peneire a goma de tapioca sobre uma frigideira antiaderente fria, cobrindo o fundo.','Leve ao fogo médio e espere a massa se unir.','Vire a tapioca, espalhe o queijo e o tomate de um lado.','Tempere com orégano e sal e dobre ao meio.','Pressione levemente e sirva quente.'],tips:['Não precisa untar a frigideira.','Pode rechear com sobras de frango, carne ou legumes.'],impact:{wasteAvoided_g:0}},
      {id:'bolinho-arroz',title:'Bolinho de Arroz com Talos',desc:'Clássico da cozinha de aproveitamento para usar sobras de arroz e talos.',image:'img/bolinho-arroz.png',type:'lanche',tags:['vegetariana'],time:25,difficulty:'fácil',yield:'15 bolinhos',ingredients:['2 xícaras de arroz cozido','1/2 xícara de talos de salsinha e cebolinha picados','1/2 xícara de queijo ralado','2 ovos','1/2 xícara de farinha de trigo','Sal e pimenta a gosto','Óleo para fritar'],steps:['Misture todos os ingredientes (exceto o óleo) em uma tigela até formar uma massa.','Modele bolinhas com a ajuda de duas colheres.','Frite em óleo quente até dourarem.','Escorra em papel toalha.'],tips:['Pode ser feito na airfryer para uma versão mais saudável.','Varie os temperos, adicionando cúrcuma ou páprica à massa.'],impact:{wasteAvoided_g:250}},
      {id:'chips-casca-batata',title:'Chips de Casca de Batata',desc:'Petisco crocante e delicioso feito com cascas de batata.',image:'img/chips-casca-batata.png',type:'lanche',tags:['vegano','aproveitamento'],time:25,difficulty:'fácil',yield:'2 porções',ingredients:['Cascas de 4 batatas grandes (bem lavadas)','1 colher de sopa de azeite','Sal e páprica a gosto'],steps:['Seque bem as cascas com um pano.','Misture as cascas com o azeite e os temperos.','Espalhe em uma assadeira e leve ao forno a 200°C por cerca de 15-20 minutos, ou até dourarem.','Vire na metade do tempo para assar por igual.'],tips:['Funciona também com cascas de batata doce ou mandioquinha.','Sirva com um molho de iogurte e ervas.'],impact:{wasteAvoided_g:150}},
      {id:'bolinho-casca-maca',title:'Bolinho de Chuva com Casca de Maçã',desc:'Bolinho de chuva com um toque nutritivo e sustentável da casca de maçã.',image:'img/bolinho-casca-maca.png',type:'lanche',tags:['vegetariana'],time:25,difficulty:'fácil',yield:'20 bolinhos',ingredients:['2 xícaras de farinha de trigo','1 xícara de açúcar','1 ovo','1 xícara de leite','1 colher de sopa de fermento em pó','Casca de 1 maçã picada finamente','Açúcar e canela para polvilhar'],steps:['Misture a farinha, o açúcar, o ovo, o leite e o fermento.','Incorpore a casca de maçã picada à massa.','Com uma colher, pegue porções da massa e frite em óleo quente.','Escorra e passe na mistura de açúcar e canela.'],tips:['Use maçãs orgânicas e lave bem as cascas.','A polpa da maçã pode ser usada em saladas ou vitaminas.'],impact:{wasteAvoided_g:50}},
      {id:'torrada-talhos',title:'Torrada com Pasta de Talos',desc:'Entrada saborosa e sustentável com pasta de talos de vegetais.',image:'img/torrada-talhos.png',type:'lanche',tags:['vegetariana'],time:15,difficulty:'fácil',yield:'4 porções',ingredients:['4 fatias de pão italiano','1 xícara de pasta de talos de brócolis (ver receita de pesto)','Tomate cereja cortado ao meio','Folhas de manjericão','Azeite'],steps:['Torre as fatias de pão.','Esfregue um dente de alho nas torradas para dar sabor.','Passe a pasta de talos sobre cada fatia.','Decore com os tomates cereja e as folhas de manjericão.','Regue com um fio de azeite.'],tips:['Use pão amanhecido para as torradas.','A pasta pode ser feita com talos de couve-flor, cenoura, etc.'],impact:{wasteAvoided_g:120}},
      {id:'mousse-casca-laranja',title:'Mousse com Casca de Laranja',desc:'Mousse aerado com aroma intenso de laranja, utilizando a casca.',image:'img/mousse-casca-laranja.png',type:'sobremesa',tags:['vegetariana'],time:20,difficulty:'fácil',yield:'4 porções',ingredients:['1 lata de leite condensado','1 lata de creme de leite','Suco de 2 laranjas','Raspas da casca de 1 laranja (parte branca evitada)'],steps:['Bata o leite condensado, o creme de leite e o suco de laranja no liquidificador.','Incorpore as raspas de laranja à mistura.','Despeje em taças e leve à geladeira por pelo menos 2 horas.'],tips:['Use apenas a parte colorida da casca para não amargar.','As metades da laranja espremida podem ser usadas como potinhos para servir.'],impact:{wasteAvoided_g:100}},
      {id:'bolo-casca-laranja',title:'Bolo com Casca de Laranja',desc:'Bolo fofinho e aromático feito com a laranja inteira, incluindo a casca.',image:'img/bolo-casca-laranja.png',type:'sobremesa',tags:['vegetariana'],time:50,difficulty:'fácil',yield:'12 porções',ingredients:['1 laranja grande com casca','3 ovos','1 xícara de óleo','2 xícaras de açúcar','2 xícaras de farinha de trigo','1 colher de sopa de fermento em pó'],steps:['Lave bem a laranja, corte em 4 pedaços e retire as sementes e a parte branca do meio.','No liquidificador, bata a laranja com casca, os ovos e o óleo.','Despeje em uma tigela, adicione o açúcar e a farinha e misture bem.','Por último, incorpore o fermento.','Asse em forno a 180°C por cerca de 40 minutos.'],tips:['Opte por laranjas orgânicas.','A calda de açúcar e suco de laranja por cima deixa o bolo ainda mais saboroso.'],impact:{wasteAvoided_g:150}},
      {id:'mousse-chia-cacau',title:'Mousse de Chia e Cacau',desc:'Sobremesa saudável, sem lactose e que pode ser feita com leite vegetal caseiro.',image:'img/mousse-chia-cacau.png',type:'sobremesa',tags:['vegano','sem_gluten'],time:15,difficulty:'fácil',yield:'2 porções',ingredients:['1 xícara de leite de amêndoas (ou outro vegetal)','3 colheres de sopa de sementes de chia','2 colheres de sopa de cacau em pó','Mel ou agave a gosto'],steps:['Misture todos os ingredientes em um pote com tampa.','Chacoalhe bem e leve à geladeira por pelo menos 4 horas.','A chia vai inchar e criar uma consistência de mousse.','Sirva com frutas vermelhas.'],tips:['Faça seu próprio leite de amêndoas e use o resíduo para fazer farinha ou biscoitos.','Pode adicionar extrato de baunilha ou canela.'],impact:{wasteAvoided_g:0}},
      {id:'peras-assadas',title:'Peras Assadas com Canela',desc:'Sobremesa simples e elegante para aproveitar peras que estão muito maduras.',image:'img/peras-assadas.png',type:'sobremesa',tags:['vegetariana','sem_gluten'],time:30,difficulty:'fácil',yield:'4 porções',ingredients:['4 peras maduras','2 colheres de sopa de mel','1 colher de chá de canela em pó','Suco de 1/2 limão','Nozes picadas para servir'],steps:['Corte as peras ao meio e retire o miolo com as sementes.','Disponha as peras em uma assadeira com a parte cortada para cima.','Regue com o mel, o suco de limão e polvilhe a canela.','Asse em forno a 180°C por 20-25 minutos, ou até ficarem macias.','Sirva quente com nozes picadas.'],tips:['As cascas podem ser usadas para fazer chá ou aromatizar água.','Funciona bem com maçãs também.'],impact:{wasteAvoided_g:250}},
      {id:'brigadeiro-casca-banana',title:'Brigadeiro de Casca de Banana',desc:'Uma versão surpreendente e sustentável do clássico brigadeiro.',image:'img/brigadeiro-casca-banana.png',type:'sobremesa',tags:['vegetariana','aproveitamento'],time:30,difficulty:'fácil',yield:'20 brigadeiros',ingredients:['Cascas de 2 bananas (bem lavadas)','1 lata de leite condensado','1 colher de sopa de manteiga','2 colheres de sopa de chocolate em pó'],steps:['Cozinhe as cascas de banana em água até ficarem bem macias.','Escorra e bata no liquidificador com um pouco de água até formar um purê.','Em uma panela, misture o purê de casca, o leite condensado, a manteiga e o chocolate.','Cozinhe em fogo baixo, mexendo sempre, até dar o ponto de brigadeiro (desgrudando do fundo).','Deixe esfriar, enrole e passe no granulado.'],tips:['Use bananas orgânicas.','Quanto mais madura a banana, mais doce a casca.'],impact:{wasteAvoided_g:100}},
      {id:'torta-casca-banana',title:'Torta de Casca de Banana',desc:'Torta nutritiva e saborosa que aproveita integralmente a banana.',image:'img/torta-casca-banana.png',type:'sobremesa',tags:['vegetariana'],time:50,difficulty:'fácil',yield:'10 porções',ingredients:['4 bananas com casca','4 ovos','1/2 xícara de óleo','2 xícaras de açúcar','2 xícaras de farinha de rosca','1 colher de sopa de fermento'],steps:['Bata no liquidificador as bananas com casca, os ovos e o óleo.','Despeje em uma tigela e adicione o açúcar e a farinha de rosca.','Misture bem e incorpore o fermento.','Asse em forma untada a 180°C por 40 minutos.','Polvilhe açúcar e canela por cima.'],tips:['Use bananas bem maduras para um sabor mais doce.','Lave bem as cascas antes de usar.'],impact:{wasteAvoided_g:200}},
      {id:'marmita-lentilha',title:'Marmita de Lentilha com Arroz e Legumes',desc:'Marmita vegana completa, rica em proteínas e fibras.',image:'img/marmita-lentilha.png',type:'marmita',tags:['vegano','sem_gluten'],time:40,difficulty:'fácil',yield:'4 marmitas',ingredients:['1 xícara de lentilha cozida','2 xícaras de arroz integral cozido','2 xícaras de legumes cozidos no vapor (brócolis, cenoura)','Temperos a gosto (cúrcuma, cominho)'],steps:['Tempere a lentilha cozida com seus temperos preferidos.','Monte as marmitas dividindo o arroz, a lentilha e os legumes em 4 potes.','Guarde na geladeira por até 4 dias ou congele.'],tips:['Cozinhe os grãos e legumes no início da semana para facilitar a montagem.','A água do cozimento dos legumes pode virar um caldo base.'],impact:{wasteAvoided_g:0}},
      {id:'marmita-graoselegumes',title:'Marmita de Grãos e Legumes',desc:'Marmita colorida e nutritiva, ideal para almoços rápidos.',image:'img/marmita-graoselegumes.png',type:'marmita',tags:['vegano','sem_gluten'],time:30,difficulty:'fácil',yield:'3 marmitas',ingredients:['1 xícara de quinoa cozida','1 xícara de grão-de-bico cozido','1 pepino em cubos','1 pimentão vermelho em cubos','Salsinha picada','Molho: azeite, limão, sal'],steps:['Misture a quinoa e o grão-de-bico.','Adicione os legumes picados e a salsinha.','Tempere com o molho na hora de servir para não amolecer os vegetais.','Divida em potes para as marmitas.'],tips:['Deixe o molho em um potinho separado para manter a salada crocante.','Use sobras de outros grãos como cevadinha ou arroz.'],impact:{wasteAvoided_g:0}},
      {id:'marmita-frango',title:'Marmita de Frango com Batata Doce',desc:'Marmita clássica e equilibrada, rica em proteína e carboidrato complexo.',image:'img/marmita-frango.png',type:'marmita',tags:[],time:45,difficulty:'fácil',yield:'4 marmitas',ingredients:['500g de filé de frango em cubos','2 batatas doces grandes em cubos','Brócolis cozido no vapor','Temperos para o frango (alho, páprica, sal, pimenta)'],steps:['Tempere e grelhe o frango em uma frigideira ou asse no forno.','Cozinhe ou asse os cubos de batata doce.','Monte as marmitas com uma porção de frango, batata doce e brócolis.'],tips:['Asse o frango e a batata doce na mesma assadeira para economizar tempo e louça.','A casca da batata doce pode ser assada e virar chips.'],impact:{wasteAvoided_g:0}},
      {id:'marmita-tofu',title:'Marmita de Tofu Grelhado com Legumes',desc:'Marmita vegetariana saborosa e rica em proteína vegetal.',image:'img/marmita-tofu.png',type:'marmita',tags:['vegetariana','vegano'],time:30,difficulty:'fácil',yield:'3 marmitas',ingredients:['400g de tofu firme em fatias','Molho shoyu e gengibre para marinar','Legumes variados fatiados (abobrinha, cenoura, pimentão)','Arroz integral para acompanhar'],steps:['Pressione o tofu para retirar o excesso de água e deixe marinar por 15 minutos.','Grelhe o tofu e os legumes em uma frigideira quente.','Sirva com o arroz integral.'],tips:['Marinar o tofu faz toda a diferença no sabor.','Use os talos dos legumes no refogado.'],impact:{wasteAvoided_g:0}},
      {id:'marmita-frango-abobora',title:'Marmita de Frango com Abóbora',desc:'Marmita saudável e saborosa com purê de abóbora e frango desfiado.',image:'img/marmita-frango-abobora.png',type:'marmita',tags:[],time:50,difficulty:'fácil',yield:'4 marmitas',ingredients:['500g de frango cozido e desfiado','1kg de abóbora cabotiá cozida','Arroz integral cozido','Cebola, alho e cheiro-verde para refogar'],steps:['Amasse a abóbora cozida para fazer um purê.','Refogue o frango desfiado com os temperos.','Monte as marmitas com o purê, o frango e o arroz.'],tips:['Asse as sementes da abóbora para um lanche nutritivo.','Use a casca da abóbora para fazer caldos.'],impact:{wasteAvoided_g:300}},
      {id:'marmita-arroz-integral-legumes',title:'Marmita de Arroz Integral com Legumes',desc:'Marmita simples, saudável e versátil para o dia a dia.',image:'img/marmita-arroz-integral-legumes.png',type:'marmita',tags:['vegano','sem_gluten'],time:40,difficulty:'fácil',yield:'4 marmitas',ingredients:['2 xícaras de arroz integral cozido','2 xícaras de legumes picados (cenoura, vagem, milho)','1/2 xícara de grão-de-bico cozido','Temperos a gosto'],steps:['Em uma panela, refogue os legumes.','Adicione o arroz integral e o grão-de-bico e misture bem.','Tempere a gosto e divida em 4 porções.'],tips:['Adicione um fio de azeite antes de aquecer para dar mais sabor.','Use a água do cozimento dos legumes para cozinhar o arroz.'],impact:{wasteAvoided_g:0}},
      {id:'sopa-talhos',title:'Sopa dos Talos',desc:'Sopa de aproveitamento, usando talos e cascas.',image:'img/sopa-talhos.png',type:'jantar',tags:['vegano','sem_gluten'],time:40,difficulty:'fácil',yield:'4 porções',ingredients:['talos variados (salsinha, couve, etc)','sobras de legumes','1 batata','1 litro de água ou caldo','sal e pimenta'],steps:['Refogar talos e sobras em pouco óleo.','Adicionar água e cozinhar até amaciar.','Bater no liquidificador se preferir cremosa.'],tips:['Congele talos e cascas limpos para fazer caldos rápidos.','Coar e reaproveitar o caldo para risotos.'],impact:{wasteAvoided_g:250}},
      {id:'risoto-abobora',title:'Risoto de Abóbora com Sementes Tostadas',desc:'Risoto cremoso de abóbora com um toque crocante das sementes.',image:'img/risoto-abobora.png',type:'jantar',tags:['vegetariana'],time:45,difficulty:'médio',yield:'4 porções',ingredients:['1 xícara de arroz arbóreo','2 xícaras de purê de abóbora','1/2 cebola picada','1 litro de caldo de legumes','Sementes de abóbora tostadas'],steps:['Refogue a cebola, adicione o arroz e siga o processo de risoto com o caldo.','Quando o arroz estiver quase cozido, incorpore o purê de abóbora.','Sirva com as sementes de abóbora tostadas por cima.'],tips:['Use a casca e as fibras da abóbora para fazer o caldo de legumes.','Tostar as sementes realça o sabor.'],impact:{wasteAvoided_g:300}},
      {id:'berinjela-recheada',title:'Berinjela Recheada com sua Própria Polpa',desc:'Berinjela recheada de forma sustentável, sem desperdiçar a polpa.',image:'img/berinjela-recheada.png',type:'jantar',tags:['vegano','sem_gluten'],time:50,difficulty:'fácil',yield:'2 porções',ingredients:['2 berinjelas','1 tomate picado','1/2 cebola picada','Alho, sal e ervas a gosto','Azeite'],steps:['Corte as berinjelas ao meio e retire a polpa com uma colher, formando uma canoa.','Pique a polpa da berinjela e refogue com a cebola, alho e tomate.','Recheie as canoas de berinjela com o refogado.','Regue com azeite e asse a 180°C por 30 minutos.'],tips:['Não descarte os talos da berinjela, podem ser usados em caldos.','Pode adicionar proteína de soja ou lentilha ao recheio.'],impact:{wasteAvoided_g:400}},
      {id:'caldo-legumes',title:'Caldo de Legumes Caseiro com Aparas',desc:'Caldo base para diversas receitas, feito com cascas e talos de vegetais.',image:'img/caldo-legumes.png',type:'jantar',tags:['vegano','sem_gluten','aproveitamento'],time:60,difficulty:'fácil',yield:'2 litros',ingredients:['Cascas de 2 cenouras','Cascas de 2 cebolas','Talos de 1 maço de salsão','Talos de salsinha e coentro','Grãos de pimenta preta','2 litros de água'],steps:['Junte todas as cascas, talos e temperos em uma panela grande.','Cubra com a água e leve ao fogo.','Deixe ferver e depois cozinhe em fogo baixo por pelo menos 1 hora.','Coe o caldo, descartando os sólidos.','Use imediatamente ou congele em porções.'],tips:['Mantenha um saco no congelador para ir guardando as aparas de vegetais.','Não adicione sal ao caldo, tempere a receita final.'],impact:{wasteAvoided_g:500}},
      {id:'pesto-talhos-brocolis',title:'Pesto de Talos de Brócolis',desc:'Pesto delicioso e econômico que substitui o manjericão por talos de brócolis.',image:'img/pesto-talhos-brocolis.png',type:'jantar',tags:['vegetariana','aproveitamento'],time:15,difficulty:'fácil',yield:'1 xícara',ingredients:['Talos de 1 maço de brócolis','1/2 xícara de castanhas ou amendoim','1/2 xícara de queijo parmesão ralado','1 dente de alho','1/2 xícara de azeite','Sal e pimenta'],steps:['Cozinhe os talos de brócolis em água fervente por 3 minutos para amolecer.','Escorra e passe na água fria para manter a cor.','Bata os talos, as castanhas, o queijo e o alho em um processador.','Com o processador ligado, vá adicionando o azeite em fio até formar uma pasta.','Tempere com sal e pimenta.'],tips:['As folhas do brócolis também podem ser usadas.','Sirva com massas, torradas ou em sanduíches.'],impact:{wasteAvoided_g:200}},
      {id:'nhoque-abobora',title:'Nhoque de Abóbora Sustentável',desc:'Nhoque leve feito com abóbora e farinha de aveia.',image:'img/nhoque-abobora.png',type:'jantar',tags:['vegetariana'],time:50,difficulty:'médio',yield:'4 porções',ingredients:['500g de abóbora cozida e amassada','1 xícara de farinha de aveia (aprox.)','1 ovo (opcional)','sal e noz-moscada'],steps:['Misture abóbora e farinha até dar ponto.','Modele e cozinhe os nhoques em água fervente.','Sirva com molho de tomate ou manteiga e sálvia.'],tips:['Ajuste a farinha conforme a umidade da abóbora.','Use cascas de abóbora para caldos antes de cozinhar a polpa.'],impact:{wasteAvoided_g:200}}
    ];

    // --- 2. DADOS DOS FILTROS ---
    const FILTERS = ['cafe','almoco','lanche','jantar','sobremesa','marmita','vegetariana','vegano','sem_gluten'];

    // --- 3. ELEMENTOS DO DOM (PÁGINA) ---
    const searchInput = document.getElementById('searchInput');
    const filtersContainer = document.getElementById('filters');
    const recipesListContainer = document.getElementById('recipesList');
    const modal = document.getElementById('modal');
    const closeModalBtn = document.getElementById('closeModalBtn');

    // Funções (createFilterChips, renderRecipes, openModal, closeModal)
    function createFilterChips() {
        if (!filtersContainer) return;
        FILTERS.forEach(filter => {
            const button = document.createElement('button');
            button.className = 'filter-chip';
            button.textContent = filter.replace('_',' ');
            button.dataset.filter = filter;
            button.onclick = () => { 
                button.classList.toggle('active'); 
                renderRecipes(); 
            };
            filtersContainer.appendChild(button);
        });
    }

    function renderRecipes() {
        if (!recipesListContainer) return;
        const query = searchInput.value.trim().toLowerCase();
        const activeFilters = Array.from(document.querySelectorAll('.filter-chip.active')).map(el => el.dataset.filter);
        
        recipesListContainer.innerHTML = '';

        const filteredRecipes = RECIPES.filter(recipe => {
            const searchString = `${recipe.title} ${recipe.desc || ''} ${(recipe.tags || []).join(' ')} ${(recipe.ingredients || []).join(' ')}`.toLowerCase();
            const matchesQuery = searchString.includes(query);
            const matchesFilters = activeFilters.every(filter => (
                recipe.type === filter || (recipe.tags && recipe.tags.includes(filter))
            ));
            return matchesQuery && matchesFilters;
        });

        if (filteredRecipes.length === 0) {
            recipesListContainer.innerHTML = '<div class="no-results">Nenhuma receita encontrada.</div>';
            return;
        }

        filteredRecipes.forEach(r => {
            const recipeCard = document.createElement('article');
            recipeCard.className = 'card';
            recipeCard.innerHTML = `
                <img src="${r.image}" alt="${r.title}">
                <div class="content">
                    <h4 class="k">${r.title}</h4><div class="desc">${r.desc || ''}</div>
                    <div class="meta"><span>⏱ ${r.time || '?'} min • ${r.difficulty || '?'}</span><span class="badge-impact">♻ ${r.impact?.wasteAvoided_g || 0}g</span></div>
                    <div class="card-footer">
                      <div class="tag-list">${[r.type, ...(r.tags || [])].join(', ')}</div>
                      <div><button class="btn btn-primary" onclick="openModal('${r.id}')">Abrir</button></div>
                    </div>
                </div>`;
            recipesListContainer.appendChild(recipeCard);
        });
    }

    function openModal(id) {
        if (!modal) return;
        const recipe = RECIPES.find(r => r.id === id);
        if (!recipe) return;
        
        document.getElementById('modalTitle').textContent = recipe.title || '';
        document.getElementById('modalImage').src = recipe.image || '';
        document.getElementById('modalDesc').textContent = recipe.desc || '';
        document.getElementById('modalTime').textContent = `⏱ ${recipe.time || '?'} min`;
        document.getElementById('modalDiff').textContent = `Nível: ${recipe.difficulty || '?'}`;
        document.getElementById('modalYield').textContent = `Rende: ${recipe.yield || '?'}`;
        document.getElementById('modalImpact').textContent = `♻ ${recipe.impact?.wasteAvoided_g || 0}g evitados`;
        
        const createListItems = (items) => (items || []).map(i => `<li>${i}</li>`).join('');
        document.getElementById('modalIngredients').innerHTML = createListItems(recipe.ingredients);
        document.getElementById('modalSteps').innerHTML = createListItems(recipe.steps);
        document.getElementById('modalTips').innerHTML = createListItems(recipe.tips);
        
        modal.classList.add('show');
    }
    window.openModal = openModal;

    function closeModal() {
        if (modal) modal.classList.remove('show');
    }

    // --- 4. INICIALIZAÇÃO E EVENTOS ---
    if (searchInput) searchInput.addEventListener('input', renderRecipes);
    if (closeModalBtn) closeModalBtn.addEventListener('click', closeModal);
    if (modal) modal.addEventListener('click', (event) => {
        if (event.target === modal) {
            closeModal();
        }
    });
    
    // Inicia as funções principais
    createFilterChips();
    renderRecipes();

});